iWant_proj/iWant/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^home/$', views.index, name='home'),
    url(r'^signup/$', views.sign_up, name='signup'),
    url(r'^new-account/$', views.create_account, name='newaccount'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^login/$', views.sign_in, name='login'),
    url(r'^logout/$', views.sign_out, name='logout'),
    url(r'^create-wish/$', views.new_wish, name='create'),
    url(r'^wish-added/$', views.add_wish, name='add'),
    url(r'^(?P<wish_id>[0-9]+)/$', views.detail, name='detail'),
]

# Handle signup and profile in one link.

iWant_proj/iWant_proj/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^iWant/', include('iWant.urls', namespace="iWant")),

]

iWant_proj/iWant/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from django.utils import timezone
import pytz

class Wish(models.Model):
    creator = models.ForeignKey(User)
    item = models.CharField(max_length=50)
    brand = models.CharField(max_length=50, default='')
    condition = models.CharField(max_length=50, default='')
    created_date = models.DateTimeField()
    details = models.TextField(default='')

    def __str__(self):
        return self.item

    class Meta:
        ordering = ('-created_date',)

iWant_proj/iWant/views.py
from django.shortcuts import render
import datetime
import pytz
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.template.context_processors import csrf
from .models import User, Wish
from ebaysdk.finding import Connection as Finding

def index(request):
    if request.user.is_authenticated():
        context = {'logged_in': True}
    else:
        context = {'logged_in': False}
    return render(request, 'iWant/index.html', context)

def sign_up(request):
    return render(request, 'iWant/login.html')

def sign_in(request):
    return render(request, 'iWant/login.html')

def username_exists(username):
    if User.objects.filter(username=username).count():
        return True
    else:
        return False

def email_exists(email):
    if User.objects.filter(email=email).count():
        return True
    else:
        return False

def password_valid(password):
    one_letter = False
    one_number = False
    for char in password:
        # Check for number.
        if char.isdigit():
            one_number = True
        # Check for letter.
        if char.isalpha():
            one_letter = True
    if one_letter and one_number:
        return True
    else:
        return False

def create_account(request):
    if request.method == "GET":
        return render(request, 'iWant/login.html')
    if request.method == "POST":
        fName = request.POST.get('firstname', '')
        lName = request.POST.get('lastname', '')
        userEmail = request.POST.get('email', '')
        uName = request.POST.get('username', '')
        uPwd = request.POST.get('password', '')
        uPwdConfirm = request.POST.get('confirm-password', '')
    if username_exists(uName):
        context = {'error_usernameTaken': True}
        return render(request, 'iWant/login.html', context)
    if email_exists(userEmail):
        context = {'error_emailExists': True}
        return render(request, 'iWant/login.html', context)
    # if not password_valid(uPwd):
    #     context = {'error_passwordStructure': True}
    #     return render(request, 'iWant/login.html', context)
    if (fName == '' or lName == '' or userEmail == '' or uName == '' or 
        uPwd == '' or uPwdConfirm == ''):
        context = {'incomplete_fields': True}
        return render(request, 'iWant/login.html', context)
    if (uPwd) != (uPwdConfirm):
        context = {'password_mismatch': True}
        return render(request, 'iWant/login.html', context)
    new_user = User.objects.create_user(username=uName, email=userEmail, 
        password=uPwd, first_name=fName, last_name=lName)
    # Customize login screen to include user information (i.e. full name).
    user = request.user
    all_wishes = user.wish_set.all()
    context = {'user': user, 'wishes': all_wishes}
    return render(request, 'iWant/profile.html', context)

def profile(request):
    if not request.user.is_authenticated():
        # Never crashes if there is no POST data. Will revert to empty string.
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                # Creates a user session.
                login(request, user)
                # Create context to customize profile with welcome text using 
                #the user's information (i.e. full name).
                user = User.objects.get(username=username)
                wishes = user.wish_set.all()
                context = {'wishes': wishes}
                context['just_logged_in'] = True
                return render(request, 'iWant/profile.html', context)
            else:
                # Create provision for disabled accounts that violated terms of 
                # use.
                context = {'disabled': True}
                return render(request, 'iWant/login-page.html', context)
        else:
            # Redirect back to the login page if username and/or password
            # credentials are incorrect.
            context = {'incorrect_creds': True}
            return render(request, 'iWant/login.html', context)
    # If the user is already logged in, allow him/her to access the profile
    # page directly without further authentication processes.
    else:
        user = request.user
        all_wishes = user.wish_set.all()
        context = {'user': user, 'wishes': all_wishes}
        return render(request, 'iWant/profile.html', context)

def new_wish(request):
    context = {}
    return render(request, 'iWant/new-wish.html', context)

def add_wish(request):
    if request.method == "POST":
        user = request.user
        full_name = user.get_full_name()
        item = request.POST.get('item', '')
        brand = request.POST.get('brand', '')
        condition = request.POST.get('condition', '')
        created_date = datetime.datetime.now(pytz.utc)
        details = request.POST.get('details', '')
        # Perform form validation, and send the user back to the Create Zuppl
        # page if there were any missing fields.
        if (item == ''):
            context = {'missed_field': True}
            return render(request, 'iWant/new-wish.html', context)
        else:
            new_wish = Wish(creator=user, item=item, 
                brand=brand, condition=condition, created_date=created_date,
                details=details)
            new_wish.save()
    wish_list = user.wish_set.all()
    context = {'wishes': wish_list}
    return render(request, 'iWant/profile.html', context)

def getDetails(name):
  time1Start = '2015-09-19T00:00:00.000Z'
  time1End = '2015-09-19T23:59:59.999Z'
  time2Start = '2015-09-20T00:00:00.000Z'
  time2End = '2015-09-20T23:59:59.999Z'
  time3Start = '2015-09-21T00:00:00.000Z'
  time3End = '2015-09-21T23:59:59.999Z'
  time4Start = '2015-09-22T00:00:00.000Z'
  time4End = '2015-09-22T23:59:59.999Z'
  time5Start = '2015-09-23T00:00:00.000Z'
  time5End = '2015-09-23T23:59:59.999Z'
  time6Start = '2015-09-24T00:00:00.000Z'
  time6End = '2015-09-24T23:59:59.999Z'
  time7Start = '2015-09-25T00:00:00.000Z'
  time7End = '2015-09-25T23:59:59.999Z'
  time8Start = '2015-09-26T00:00:00.000Z'
  time8End = '2015-09-26T14:40:00.000Z'
  d1 = findItem(name, time1Start, time1End)
  d2 = findItem(name, time2Start, time2End)
  d3 = findItem(name, time3Start, time3End)
  d4 = findItem(name, time4Start, time4End)
  d5 = findItem(name, time5Start, time5End)
  d6 = findItem(name, time6Start, time6End)
  d7 = findItem(name, time7Start, time7End)
  d8 = findItem(name, time8Start, time8End)
  l = []
  l.append(findAvgPriceForOneDay(d1))
  l.append(findAvgPriceForOneDay(d2))
  l.append(findAvgPriceForOneDay(d3))
  l.append(findAvgPriceForOneDay(d4))
  l.append(findAvgPriceForOneDay(d5))
  l.append(findAvgPriceForOneDay(d6))
  l.append(findAvgPriceForOneDay(d7))

  today = findAvgPriceForOneDay(d8)
  avg = round(average(l),2)
  return (l, today, avg)

def findItem(name, timeStart, timeEnd):
  api = Finding(appid='VarunRam-29e8-46c1-87ef-dbcf272585f7', 
                config_file =None)
  api_request = {
      'keywords': name,
      'sortOrder': 'EndTimeSoonest',
      'itemFilter': {
        'name': 'SoldItemsOnly',
        'value': 'true',
        'name':'EndTimeFrom',
        'value':timeStart,
        'name':'EndTimeTo',
        'value':timeEnd
      }
  }
  response = api.execute('findCompletedItems', api_request)

  assert(response.reply.ack == 'Success')
  return response.dict()

def average(l):
  if l == []:
    return 0
  return sum(l) / len(l)

def findAvgPriceForOneDay(d):
  itemList = d['searchResult']['item']
  priceList = []
  for item in itemList:
    priceList.append(round(float(item['sellingStatus']['convertedCurrentPrice']['value']),2))
  #print
  pListLength = len(priceList)
  priceList.sort()
  priceList = priceList[pListLength//4 : 3*pListLength//4]
  #print(priceList)
  return round(average(priceList),2)

def findCurrentItem(name):
  api = Finding(appid='VarunRam-29e8-46c1-87ef-dbcf272585f7', 
                config_file =None)
  api_request = {
      'keywords': name,
      'sortOrder': 'CurrentPriceHighest',
  }
  response = api.execute('findCompletedItems', api_request)

  assert(response.reply.ack == 'Success')
  return response.dict()

def sortFinalList(finalList, avg, name):
  finalList.sort(key = lambda x: abs(x[0] - avg))

def getBestThree(name, avg):
  d = findCurrentItem(name)
  itemList = d['searchResult']['item']
  item1Url = itemList[0]['viewItemURL']
  item1Price = round(float(itemList[0]['sellingStatus']['convertedCurrentPrice']['value']),2)
  item1Name = itemList[0]['title']
  item2Url = itemList[1]['viewItemURL']
  item2Name = itemList[1]['title']
  item2Price = round(float(itemList[1]['sellingStatus']['convertedCurrentPrice']['value']),2)
  item3Url = itemList[2]['viewItemURL']
  item3Name = itemList[2]['title']
  item3Price = round(float(itemList[2]['sellingStatus']['convertedCurrentPrice']['value']),2)
  maxDifference = max(abs(item1Price- avg), abs(item2Price- avg), abs(item3Price- avg))
  finalList = []
  finalList.append((item1Price,item1Url, item1Name))
  finalList.append((item2Price,item2Url, item2Name))
  finalList.append((item3Price,item3Url, item3Name))
  sortFinalList(finalList, avg, name)
  for i in range(3, len(itemList)):
    url = itemList[i]['viewItemURL']
    price = round(float(itemList[i]['sellingStatus']['convertedCurrentPrice']['value']),2)
    name = itemList[i]['title']
    diff = abs(price - avg)
    if diff < abs(finalList[2][0] - avg):
      finalList[2] = (price, url, name)
      sortFinalList(finalList, avg, name)
  return finalList

def detail(request, wish_id):
    wish = Wish.objects.get(id=wish_id)
    queryStr = wish.brand + ' ' + wish.item + ' ' + wish.details
    returnData = getDetails(queryStr)
    aggregateData, averageToday, averageWeek = returnData

iWant_proj/iWant/templates/iWant/login.html
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
<title>Responsive Tabs Form a Form Responsive Widget Template  :: w3layouts</title>
<link href="css/style.css" rel='stylesheet' type='text/css' />
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Tab Form,Login Forms,Sign up Forms,Registration Forms,News latter Forms,Elements"./>
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
</script>
<meta name="description" content="Login Page">
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'iWant/css/bootstrap.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'iWant/css/bootstrap.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'iWant/css/landing-page.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'iWant/css/style.css' %}" />
<script type="text/javascript" src="{% static 'iWant/js/bootstrap.js' %}"></script>
<script type="text/javascript" src="{% static 'iWant/js/bootstrap.min.js' %}"></script> 
<script type="text/javascript" src="{% static 'iWant/js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'iWant/js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'iWant/js/easyResponsiveTabs.js' %}"></script>
				<script type="text/javascript">
					$(document).ready(function () {
						$('#horizontalTab').easyResponsiveTabs({
							type: 'default', //Types: default, vertical, accordion           
							width: 'auto', //auto or any width like 600px
							fit: true   // 100% fit in a container
						});
					});
				   </script>

<!--webfonts-->
<link href='//fonts.googleapis.com/css?family=Nixie+One' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,600,700,200italic,300italic,400italic,600italic|Lora:400,700,400italic,700italic|Raleway:400,500,300,600,700,200,100' rel='stylesheet' type='text/css'>
<!--//webfonts-->
<link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
<link href="http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand topnav" href="{% url 'iWant:home' %}">iWant</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        {% if user.is_authenticated %}
          				<li><a href="{% url 'iWant:profile' %}">My Wish List</a></li>
          				{% else %}
          				<li><a href="{% url 'iWant:login' %}">My Wish List</a></li>
          				{% endif %}
                    </li>
                    <li>
                        {% if user.is_authenticated %}
          				<a href="{% url 'iWant:create' %}">Create New Wish</a>
          				{% else %}
          				<a href="{% url 'iWant:login' %}">Create New Wish</a>
          				{% endif %}
                    </li>
                    <li>
                    	{% if user.is_authenticated %}
          				<li><a href="{% url 'iWant:logout' %}">Sign Out</a></li>
          				{% else %}
          				<li><a href="{% url 'iWant:login' %}">Sign In</a></li>
          				{% endif %}
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

<div class="main">
		<h2>Welcome</h2>
	 <div class="sap_tabs">	
		 <div id="horizontalTab" style="display: block; width: 100%; margin: 0px;">
			  <ul class="resp-tabs-list">
			  	  <li class="resp-tab-item" aria-controls="tab_item-0" role="tab"><span>Sign up</span></li>
				  <li class="resp-tab-item" aria-controls="tab_item-1" role="tab"><span>Sign in</span></li>
				  <div class="clear"></div>
			  </ul>		
			  <!---->		  	 
			 <div class="resp-tabs-container">
				  <div class="tab-1 resp-tab-content" aria-labelledby="tab_item-0">
							<div class="facts">
									<!--login1-->
								<div class="register">
									<form action="{% url 'iWant:newaccount' %}" method="post" role="form">
									{% csrf_token %}
										<input name="firstname" placeholder="First Name" type="text" required="">
										<input name="lastname" placeholder="Last Name" type="text" required="">
										<input name="email" placeholder="Email Address" type="text" required="">
										<input name="username" placeholder="Username" type="text" required="">
										<input name="password" placeholder="Password" type="password" required="">	
										<input name="confirm-password" placeholder="Confirm Password" type="password" required="">
										<div class="sign-up">
											<input type="submit" value="Create Account"/>
										</div>
									</form>
								</div>
							</div>
				 </div>		
				 <div class="tab-2 resp-tab-content" aria-labelledby="tab_item-1">
					  <div class="facts">
						  <div class="register">
									<form action="{% url 'iWant:profile' %}" method="post" role="form">	
									{% csrf_token %}
										<input name="username" placeholder="Username" class="mail" type="text" required="">			
										<input name="password" placeholder="Password" class="lock" type="password" required="">										
										<div class="sign-up">
											<input type="submit" value="Submit"/>
										</div>
									</form>
								</div>
					  </div> 
				  </div> 			        					            	      
			  </div>	
		  </div>	
	 </div>
	 <!--start-copyright-->
   		<div class="copy-right">
   			<div class="wrap">
				<p>Copyright &copy; 2015 Responsive Tabs Form.  All rights  Reserved | Design by <a href="http://w3layouts.com">W3layouts</a></p>
		</div>
	</div>
	<!--//end-copyright-->
</div>	
</body>
</html>

iWant_proj/iWant/templates/iWant/new-wish.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="">

    <title>iWant Homepage</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/landing-page.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <meta name="description" content="iWant Homepage">
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'iWant/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'iWant/css/bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'iWant/css/landing-page.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'iWant/css/main2.css' %}" />
    <script type="text/javascript" src="{% static 'iWant/js/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'iWant/js/bootstrap.min.js' %}"></script> 
    <script type="text/javascript" src="{% static 'iWant/js/jquery.js' %}"></script>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand topnav" href="{% url 'iWant:home' %}">iWant</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        {% if user.is_authenticated %}
                        <li><a href="{% url 'iWant:profile' %}">My Wish List</a></li>
                        {% else %}
                        <li><a href="{% url 'iWant:login' %}">My Wish List</a></li>
                        {% endif %}
                    </li>
                    <li>
                        {% if user.is_authenticated %}
                        <a href="{% url 'iWant:create' %}">Create New Wish</a>
                        {% else %}
                        <a href="{% url 'iWant:login' %}">Create New Wish</a>
                        {% endif %}
                    </li>
                    <li>
                        {% if user.is_authenticated %}
                        <li><a href="{% url 'iWant:logout' %}">Sign Out</a></li>
                        {% else %}
                        <li><a href="{% url 'iWant:login' %}">Sign In</a></li>
                        {% endif %}
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
<br><br><br><br><br>
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="panel panel-login">
            <div class="panel-heading">
              <div class="row">
                <div class="col-xs-12">
                  <h3 align="center">Create Wish</h3>
                </div>
              </div>
              <hr>
            </div>
            <div class="panel-body">
              <div class="row">
                <div class="col-lg-12">
                  <form id="register-form" action="{% url 'iWant:add' %}" method="post" role="form" style="display: block;">
                  {% csrf_token %}
                    <div class="form-group">
                      <label for="name">Item Name</label>
                      <input type="text" name="item" id="eventname" tabindex="1" class="form-control" placeholder="Name" value="">
                    </div>
                    <div class="form-group">
                      <label for="brand">Brand</label>
                      <input type="text" name="brand" id="brand" tabindex="1" class="form-control" placeholder="(Optional)" value="">
                    </div>
                    <div class="form-group">
                      <label for="brand">Condition</label>
                      <input type="text" name="condition" id="condition" tabindex="1" class="form-control" placeholder="(Optional)" value="">
                    </div>
                    <div class="form-group">
                      <label for="details">Details</label>
                      <textarea type="textarea" name="details" id="details" tabindex="2" rows="4" cols="60" class="form-control" placeholder="Enter additional information here"></textarea>
                    </div>
                    <div class="form-group">
                      <div class="row">
                        <div class="col-sm-6 col-sm-offset-3">
                          <input type="submit" name="iWant_submit" id="iWant_submit" tabindex="4" class="form-control btn btn-primary" value="Create Wish">
                        </div>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</body>

iWant_proj/iWant/templates/iWant/profile.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="">

    <title>iWant Homepage</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/landing-page.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <meta name="description" content="iWant Homepage">
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'iWant/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'iWant/css/bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'iWant/css/landing-page.css' %}" />
    <script type="text/javascript" src="{% static 'iWant/js/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'iWant/js/bootstrap.min.js' %}"></script> 
    <script type="text/javascript" src="{% static 'iWant/js/jquery.js' %}"></script>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand topnav" href="{% url 'iWant:home' %}">iWant</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        {% if user.is_authenticated %}
                        <li><a href="{% url 'iWant:profile' %}">My Wish List</a></li>
                        {% else %}
                        <li><a href="{% url 'iWant:login' %}">My Wish List</a></li>
                        {% endif %}
                    </li>
                    <li>
                        {% if user.is_authenticated %}
                        <a href="{% url 'iWant:create' %}">Create New Wish</a>
                        {% else %}
                        <a href="{% url 'iWant:login' %}">Create New Wish</a>
                        {% endif %}
                    </li>
                    <li>
                        {% if user.is_authenticated %}
                        <li><a href="{% url 'iWant:logout' %}">Sign Out</a></li>
                        {% else %}
                        <li><a href="{% url 'iWant:login' %}">Sign In</a></li>
                        {% endif %}
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <div class="container">
    <br><br><br><br><br>
      {% if just_logged_in %}
      <h1 class="page-title" align="center" style="text-decoration:underline; font-size:2em;">You are now logged in, {{user.first_name}}. Here are your wishes.</h1>
      {% else %}
      <h1 class="page-title" align="center" style="text-decoration:underline; font-size:2em;">Hi, {{user.first_name}}! These are your wishes.</h1>
      {% endif %}
      <br><br><br>

{% for wish in wishes %}
  <div class="col-md-4 col-md-offset-4 wish-box">
    <div class="row">
      <div class="col-md-6 col-md-offset-3" align="center" style="font-size:2em;">
        <a href="{% url 'iWant:detail' wish.id %}">{{wish.item}}</a>
      </div>
      <div class="col-md-6 col-md-offset-3" align="center" style="font-size:1.2em;">
        <p class="wish-brand">By {{wish.brand}}</p>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <p align="center">Details: {{wish.details}}</p>
      </div>
    </div>
  </div>
  {% endfor %}